DROP TABLE IF EXISTS tabla_auxiliar;
CREATE TABLE tabla_auxiliar (
    id INT PRIMARY KEY
);

INSERT INTO tabla_auxiliar (id)
SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 + 1 AS num
FROM 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
CROSS JOIN 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
CROSS JOIN 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
CROSS JOIN 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
CROSS JOIN 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
WHERE a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 < 10000;

INSERT INTO Empleado (nombre, dni, email, fecha_ingreso, area)
SELECT 
    CONCAT('Empleado_', LPAD(id, 7, '0')),
    CONCAT('DNI', LPAD(id, 8, '0')),
    CONCAT('empleado', LPAD(id, 7, '0'), '@ejemplo.com'),
    DATE_ADD('2010-01-01', INTERVAL FLOOR(RAND() * 3650) DAY),
    CASE 
        WHEN RAND() < 0.3 THEN 'Desarrollo'
        WHEN RAND() < 0.6 THEN 'Ventas'
        ELSE 'Marketing'
    END
FROM tabla_auxiliar;

INSERT INTO Legajo (nro_legajo, categoria, estado, fecha_alta, observaciones, id_empleado)
SELECT
    CONCAT('LEG', LPAD(id, 7, '0')),
    CASE 
        WHEN RAND() < 0.3 THEN 'CANDIDATO'
        WHEN RAND() < 0.6 THEN 'TEMPORAL'
        ELSE 'PERMANENTE'
    END,
    'ACTIVO',
    CURDATE(),
    CONCAT('Legajo del empleado ', CONCAT('Empleado_', LPAD(id, 7, '0'))),
    id
FROM tabla_auxiliar;